### ISSUE TITLE
Broken/Outdated conference websites

### ISSUE THREAD

**Issue by The-Compiler** [PyCon/pycon.org#15]
Looking at the list on http://pycon.org/ a few websites seem to be broken:

- [Belarus](https://by.pycon.org/) sends an invalid SSL certificate (valid for https://eventspace.by/)
- [Cameroon](http://pyconcameroon.org/) shows a "Website Unavailable" page
- [Danemark](http://pycon.dk/) shows some domain parking website (I think) which is unrelated to Python
- [Uruguay](http://pycon.python.org.uy) doesn't resolve
- [Venezuela](http://ve.pycon.org) doesn't resolve
- [Finland](http://python.fi/toiminta/pyconfi/) apparently stopped organizing conferences in 2016
- [Namibia](http://python-namibia.org/) also talks about 2015

Some of those maybe should be removed?

**Comment by glasnt** [comment]
Thanks for this @The-Compiler. I'll work to update the URLs where I can.

**Comment by glasnt** [comment]
Notes: 
Finland does at least resolve, but as noted, hasn't run for a year or two
Venezuela doesn't have a valid URL, but does have a twitter. Unsure if we should link to that.  (@lorenanicole, thoughts?)
Denmark isn't showing anything useful in a cursory search. 



Updates found for: Namibia, Cameroon, Uruguay. Belarus also now live.

**Comment by lorenanicole** [comment]
@glasnt my preference would be that we somehow build in for conferences into our PR flow something like:

- What is the URL of your conference?
- Does this URL change annually?
- If yes, what is the pattern?

We can make that part of the PR template .... and maybe add some automation in such that if there's something like a `http://{year}.{pycon-domain}.com` preference we can update the year ever Dec 31 or something ... 🤷‍♀ 

And for including twitter, why don't we just ask for more info from the conf to begin with?

**Comment by glasnt** [comment]
I think I would prefer linking to a top-level where possible. Eg. PyCon AU's top level domain resolves to the current year and is manually changed when needed. The overhead of keeping on top of annual changes seems, to me, of little added value.

**Comment by JeppeKlitgaard** [comment]
The Danish site `pycon.dk` is being used to host sponsored articles and bears no mention of Python. It doesn't appear to have any original content and is likely just using the traffic generated from the pycon.org site for profit.

The articles also seem to be very questionable in nature and I believe they may also in violation of Danish advertising laws.

Please consider removing `pycon.dk` from the site.
