### ISSUE TITLE
Update mention of PyCon North America

### ISSUE THREAD

**Issue by brainwane** [PyCon/pycon.org#21]
https://github.com/PyCon/pycon.org/blob/6ff5b2ac4404913c4faa8d10f43c279ecea46239/index.html#L66 should mention 2019's PyCon in the past tense. And, per https://twitter.com/pycon/status/1155940871952457728 , it should say that PyCon North America will be April 15 - 23, 2020 in Pittsburgh. The events calendar should also include this.

**Comment by jefftriplett** [comment]
This is resolved in 1a831fc697ecdacf9dfd183d9252da95dad17d5a :tada:
